name: Main

on:
  pull_request:
    types: [opened, synchronize, reopened]
  push:
    branches: [main]

jobs:
  tests:
    strategy:
      matrix:
        python-version: ["3.12"]
        os: ["ubuntu-latest", "macos-latest", "windows-latest"]

    runs-on: ${{ matrix.os }}

    defaults:
      run:
        working-directory: .

    name: Python ${{ matrix.python-version }} on ${{ matrix.os }}

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up the uv environment
        uses: ./.github/actions/setup-uv-env
        with:
          python-version: ${{ matrix.python-version }}

      - name: Run pre-commit
        env:
          MPLBACKEND: Agg
        run: uv run --extra dev pre-commit run -a --show-diff-on-failure

      - name: Install nox
        run: uv pip install nox
        shell: bash

      - name: Run nox
        run: nox --pythons ${{ matrix.python-version }}
        shell: bash

      - name: Run tests
        env:
          MPLBACKEND: Agg
        run: uv run --extra test python -m pytest tests/ -v --cov=graph_lp --cov-report=term-missing
